---
#
# EECS 4287/5287: Principles of Cloud Computing
# Author: Aniruddha Gokhale
# Created: Fall 2020
# Modified: Fall 2020  to use new approach
#
# This playbook will execute a command on the remote machine
# Horizon Cloud VM or Chameleon VMs or AWS VMs
# See https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
- hosts: MyChameleonVMs
  remote_user:  cc   # change the user to whatever is the user on the cloud VM
  collections:   # this is new starting with Ansible 2.9 (akin to importing package)
    - openstack.cloud
  become: yes
  
  tasks:
    - name: Start Zookeeper Service
      shell: "bin/zookeeper-server-start.sh  config/zookeeper.properties"
      when: inventory_hostname == play_hosts[0]
      async: 86400 #Run for 24hours
      poll: 0

    - name: Start Kafka Service
      shell: "bin/kafka-server-start.sh  config/server.properties"
      async: 86400
      poll: 0

    - name: Create Kafka Topic
      shell: "bin/kafka-topics.sh --create --topic hghdata --bootstrap-server localhost:9092"
      async: 15
      poll: 0

...
