---
#
# Chameleon Cloud Openstack VM Ansible Playbook
# EECS 4287/5287: Principles of Cloud Computing
# Author: Camren Hall, Luke Garrett, Safet Hoxha
#
- hosts: MyLocalVMs
  collections:   # this is new starting with Ansible 2.9 (akin to importing package)
    - openstack.cloud
  tasks:
    - name: launch an instance
      openstack.cloud.server:
        state: present
        cloud: openstack
        name: teamhgh_ansible_chameleon_01
        image: CC-Ubuntu20.04
        network: CH-819381-net
        timeout: 500
        flavor: m1.small
        floating_ips:
          - 10.212.96.69
...

