---
#
# Chameleon Cloud Openstack VM Ansible Playbook
# EECS 4287/5287: Principles of Cloud Computing
# Author: Camren Hall, Luke Garrett, Safet Hoxha
#
- name: Launching Openstack Compute Instances
  hosts: MyLocalVMs
  tasks:       
    - name: Launch Instance 01
      openstack.cloud.server:
        state: present
        cloud: openstack
        name: teamhgh_ansible_chameleon_007
        image: CC-Ubuntu20.04
        flavor: m1.medium
        network: CH-819381-net
        key_name: ChameleonHGH01
        security_groups:
                - 241156b1-e189-4233-aa25-d6071b67adae
        timeout: 200
        auto_ip: yes
    - name: Launch Instance 02
      openstack.cloud.server:
        state: present
        cloud: openstack
        name: teamhgh_ansible_chameleon_008
        image: CC-Ubuntu20.04
        flavor: m1.medium
        network: CH-819381-net
        key_name: ChameleonHGH01
        security_groups:
                - 241156b1-e189-4233-aa25-d6071b67adae
        timeout: 500
        auto_ip: yes
    - name: Gather Facts
      openstack.cloud.server_info:
        cloud: openstack
        server: teamhgh*
        filters:
          vm_state: active
      register: result
      debug:
        msg: "{{ result.openstack_servers }}"
        
...

