- hosts: MyChameleonVMs
  remote_user:  cc   # change the user to whatever is the user on the cloud VM
  collections:   # this is new starting with Ansible 2.9 (akin to importing package)
    - openstack.cloud
  become: yes
  tasks:
    - name: Download kafka
      shell: "wget https://github.com/lukegarrett/cloudHGH/raw/master/apache-couchdb-3.2.0.tar.gz"

    - name: Extracting Kafka
      shell: "tar -xf apache-couchdb-3.2.0.tar.gz"