- hosts: MyChameleonVMs
  remote_user:  cc   # change the user to whatever is the user on the cloud VM
  collections:   # this is new starting with Ansible 2.9 (akin to importing package)
    - openstack.cloud
  become: yes

  tasks:

  - name: Add Apt Key for couchdb
    apt_key:
      url: https://couchdb.apache.org/repo/keys.asc  # URL to retrieve from
      state: present   # this is default
      keyring: /usr/share/keyrings/couchdb-repo-keyring.gpg
    become: yes
    #when: ansible_facts['hostname'] == "gokhale-vm3"

  # need to add repo to apt here TODO

  # This will install couchdb without any admin, etc.
  - name: Install CouchDB
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    loop:
      - couchdb
    become: yes
    #when: ansible_facts['hostname'] == "gokhale-vm3"
    