---
#
# Chameleon Cloud Openstack VM Ansible Playbook
# EECS 4287/5287: Principles of Cloud Computing
# Author: Camren Hall, Luke Garrett, Safet Hoxha
#
- name: launch a compute instance
  hosts: MyLocalVMs
  tasks:
    - name: launch an instance
      openstack.cloud.server:
        state: present
        cloud: CH-819381
        name: teamhgh_ansible_chameleon_01
        availability_zone: nova
        image: CC-Ubuntu20.04
        timeout: 200
        flavor: m1.small
        floating_ips:
          - 10.212.96.69
...

