- hosts: MyChameleonVMs
  remote_user:  cc   # change the user to whatever is the user on the cloud VM
  collections:   # this is new starting with Ansible 2.9 (akin to importing package)
    - openstack.cloud
  become: yes
  tasks:
    - name: System Update
      apt:
        update_cache: yes
        upgrade: dist

    - name: Setup Build Environment
      apt:
        name: 
          - build-essential 
          - pkg-config 
          - erlang 
          - libicu-dev 
          - libmozjs185-dev 
          - libcurl4-openssl-dev
        state: latest
        install_recommends: no
    
    - name: Download kafka
      shell: "curl \"https://github.com/lukegarrett/cloudHGH/raw/master/apache-couchdb-3.2.0.tar.gz\" -o couchdb.tgz"

    - name: Extracting Kafka
      shell: "tar -xvzf couchdb.tgz --strip 1"