FROM ubuntu:bionic

RUN apt-get -y update && apt-get install -y net-tools wget dnsutils iputils-ping iputils-tracepath iputils-arping iputils-clockdiff default-jdk python3
RUN apt-get install -y python3-dev python3-pip
RUN python3 -m pip install --upgrade pip

RUN wget https://dlcdn.apache.org/kafka/2.8.1/kafka_2.13-2.8.1.tgz
RUN zcat kafka_2.13-2.8.1.tgz | tar xpof -