---

    - name: Start Zookeeper Service
      shell: "bin/zookeeper-server-start.sh  config/zookeeper.properties"
      async: 86400 #Run for 24hours
      poll: 0

    - name: Start Kafka Service
      shell: "bin/kafka-server-start.sh  config/server.properties"
      async: 86400
      poll: 0

    - name: Create Kafka Topic
      shell: "bin/kafka-topics.sh --create --topic tweetdata --bootstrap-server localhost:9092"
      async: 15
      poll: 0

...
