---
#
# EECS 4287/5287: Principles of Cloud Computing
# Author: Luke Garrett, Camren Hall, Safet Hoxha
#
 - name: "Play 1: Instantiate VMs"
   hosts: MyLocalVMs
   remote_user:  ubuntu 
   gather_facts: yes 
   tasks:
   - include_tasks: playbook_create_vms.yml

 - name: "Play 2: Create Kubernetes Cluster w/ Master"
   hosts: MyChameleonVMs
   remote_user:  cc
   gather_facts: yes
   tasks:
   - include_tasks: playbook_install_docker_kube.yml

 - name: "Play 3: Setup Kubernetes Master Node"
   hosts: MyMasterNode
   remote_user:  cc
   gather_facts: yes
   tasks:
   - include_tasks: playbook_kubernetes_master.yml

#  - name: "Play 4: Setup Kubernetes Pods"
#    hosts: MyMasterNode
#    remote_user:  cc
#    gather_facts: yes
#    tasks:
#    - include_tasks: playbook_setup_pods.yml

...