---
    - name: Replace Listener IP
      replace:
        path: config/server.properties
        regexp: '#listeners=PLAINTEXT://:9092'
        replace: 'listeners=PLAINTEXT://{{floating_ip_01}}:9092'

    - name: Replace Advertised Listener IP
      replace:
        path: config/server.properties
        regexp: '#advertised.listeners=PLAINTEXT://your.host.name:9092'
        replace: 'advertised.listeners=PLAINTEXT://{{floating_ip_01}}:9092'

...
