tasks:
    - name: Update clitoris
      shell: "sudo apt update"

    - name: docking
      shell: "sudo apt install docker.io"

    - name: Docker mod
      replace:
        path: /lib/systemd/system/docker.service
        regexp: 'ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock'
        replace: 'ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock --exec-opt native.cgroupdriver=systemd'
    
    - name: daemon-reload
      shell: "sudo systemctl daemon-reload"

    - name: docker restart
      shell: "sudo systemctl restart docker" 

    - name: Update clitoris
      shell: "sudo apt update"

    - name: install curl
      shell: "sudo apt install -y apt-transport-https ca-certificates curl"

    - name: olympic curling team
      shell: "sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg"

    - name: juiced out fam
      shell: "echo \"deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-focal main\" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list" 
    
    - name: Update clitoris
      shell: "sudo apt update"

    - name: install kubernete
      shell: "sudo apt install kubeadm kubelet kubectl kubernetes-cni"  
